name: "Terraform"
on:
  schedule:
    - cron: '0 8 * * *' # Every day at 8
  push:
    branches:
      - 'check-for-new-certs' # for testing
jobs:
  check-aws-db-cert-changes:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "docker"
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Compare new and old cert bundles
        id: compare-certs
        run: |
          set -e -u -o pipefail
          ls
          curl --fail --location --silent --show-error https://truststore.pki.rds.amazonaws.com/eu-west-2/eu-west-2-bundle.pem --output "new-eu-west-2-bundle.pem"
          if cmp -s "eu-west-2-bundle.pem" "new-eu-west-2-bundle.pem"; then
            echo "The certificate bundle for Aurora remains the same"
            echo "cert-has-changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "The AWS certificate bundle for Aurora has changed"
            echo "cert-has-changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Notify
        if: steps.compare-certs.outputs.has-changed == 'true'
        run: |
          echo "notify us somehow"
